[package]
name = "lib-macro"
version = "0.0.1"
edition = "2021"

[lib]
  proc-macro = true

[dependencies]
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.96", features = ["full", "parsing", "proc-macro", "extra-traits"] }
