# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@slidev/parser-0.47.5" = {
      name = "_at_slidev_slash_parser";
      packageName = "@slidev/parser";
      version = "0.47.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@slidev/parser/-/parser-0.47.5.tgz";
        sha512 = "KvqOEhIFuMDu8CjAsehMNKlAnnmAn2TRHiEymc3CMadid05oWa5zgTxqEyMxUl2rjWpYs3A1yDiendZsGYs3HA==";
      };
    };
    "@slidev/types-0.47.5" = {
      name = "_at_slidev_slash_types";
      packageName = "@slidev/types";
      version = "0.47.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@slidev/types/-/types-0.47.5.tgz";
        sha512 = "X67V4cCgM0Sz50bP8GbVzmiL8DHC2IXvdKcsN7DlxHyf+/T4d9GveeGukwha5Fx3MuYeGZWKag7TFL2ZY4w54A==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "js-yaml-4.1.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-4.1.0.tgz";
        sha512 = "wpxZs9NoxZaJESJGIZTyDEaYpl0FKSA+FB9aJiyemKhMwkxQg63h4T1KJgUGHpTqPDNRcmmYLugrRjJlBtWvRA==";
      };
    };
    "prettier-3.3.2" = {
      name = "prettier";
      packageName = "prettier";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-3.3.2.tgz";
        sha512 = "rAVeHYMcv8ATV5d508CFdn+8/pHPpXeIid1DdrPwXnaAdH7cqjVbpJaT5eq4yRAFU/lsbwYwSF/n5iNrdJHPQA==";
      };
    };
  };
in
{
  prettier = nodeEnv.buildNodePackage {
    name = "prettier";
    packageName = "prettier";
    version = "3.3.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier/-/prettier-3.3.2.tgz";
      sha512 = "rAVeHYMcv8ATV5d508CFdn+8/pHPpXeIid1DdrPwXnaAdH7cqjVbpJaT5eq4yRAFU/lsbwYwSF/n5iNrdJHPQA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier is an opinionated code formatter";
      homepage = "https://prettier.io";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-slidev = nodeEnv.buildNodePackage {
    name = "prettier-plugin-slidev";
    packageName = "prettier-plugin-slidev";
    version = "1.0.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-slidev/-/prettier-plugin-slidev-1.0.5.tgz";
      sha512 = "1xaKzOAX17QAcn1roUgQIAfeio3HPYYefCgzxh6Bzk+5rJJxq0I8HUhLrUyv9nCpIP6e9CDv/yDQSdEeqqRUuA==";
    };
    dependencies = [
      sources."@slidev/parser-0.47.5"
      sources."@slidev/types-0.47.5"
      sources."argparse-2.0.1"
      sources."js-yaml-4.1.0"
      sources."prettier-3.3.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A prettier plugin for Slidev";
      homepage = "https://sli.dev";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
